spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1756510828
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  mvc:
#    static-path-pattern: /static/**    #静态资源的请求方式
#    resources:
#      static-locations: classpath:/static/  # 静态资源的配置位置，可以写成一个数组配置多个目录

logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log

# 简历路径
jianli: src/main/resources/static/jianli.pdf
# 简历名称
jlName: Java开发工程师-李朝阳-桂林理工大学本科应届生.pdf



